import Head from 'next/head'
import Main from '../components/Main/Main'

export default function Home() {
  return (
    <>
      <Head>
        <title>Optimum Car Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Images/Header_Img/logo.svg" />
      </Head>
      <Main />
    </>
  )
}
